'use strict';

(function bootstrapAiGm(root) {
  if (!root?.document || root.__khaosDndAiGm) return;
  const doc = root.document;
  const state = { payload: null, campaignId: '', preview: null, busy: false, scheduled: false };
  const invoke = (channel, payload) => root.khaos.invoke(channel, payload);
  const clean = (value, max = 4000) => String(value ?? '').replace(/\u0000/g, '').trim().slice(0, max);
  const esc = (value) => String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' })[c]);
  const notify = (message) => typeof root.toast === 'function' ? root.toast(message) : undefined;
  const selectedCampaignId = () => clean(doc.getElementById('dndCampaignSelect')?.value, 100);
  function schedule(){ if(state.scheduled)return; state.scheduled=true; root.requestAnimationFrame(()=>{state.scheduled=false; enhance();}); }
  function setBusy(value){ state.busy=Boolean(value); schedule(); }
  async function refresh(force=false){ const campaignId=selectedCampaignId(); if(!campaignId)return; if(!force&&state.payload&&state.campaignId===campaignId)return; state.campaignId=campaignId; state.payload=await invoke('dnd:ai-gm-get',{campaignId}); state.preview=null; schedule(); }
  function activeSession(){ return (state.payload?.sessions||[]).find((item)=>item.mode!=='ended')||null; }
  function sessionOptions(){ return (state.payload?.desktopSessions||[]).map((item)=>`<option value="${esc(item.id)}">${esc(item.title)} · ${esc(item.status)}</option>`).join(''); }
  function suggestionRows(turn){ const items=turn.response?.suggestions||[]; if(!items.length)return ''; return `<div class="dnd-ai-gm-suggestions"><strong>Reviewable suggestions</strong>${items.map((item)=>`<label class="dnd-ai-gm-suggestion"><input type="checkbox" data-ai-gm-suggestion="${esc(item.id)}" data-turn-id="${esc(turn.id)}" ${item.appliedAt?'disabled':''}><span><b>${esc(item.type.replace(/_/g,' '))}</b>: ${esc(item.text)} ${item.appliedAt?`<small>Applied to ${esc(item.appliedTarget)}</small>`:''}</span></label>`).join('')}<div class="dnd-ai-gm-actions"><select data-ai-gm-target="${esc(turn.id)}"><option value="session_recap">Session recap draft</option><option value="campaign_codm_notes">Campaign Co-DM notes</option></select><button class="button" data-ai-gm-action="apply" data-turn-id="${esc(turn.id)}">Apply Selected</button></div></div>`; }
  function turnCard(turn){ const safety=turn.response?.safety?.status&&turn.response.safety.status!=='ok'; return `<article class="dnd-ai-gm-turn ${esc(turn.status)} ${safety?'safety':''}"><span class="eyebrow">${esc(turn.actor)} · ${esc(turn.status)}</span><p><strong>Table input:</strong> ${esc(turn.message)}</p>${turn.status==='completed'?`<p><strong>Narration:</strong> ${esc(turn.response?.narration||'')}</p>${(turn.response?.spokenDialogue||[]).map((line)=>`<p><strong>${esc(line.speaker)}:</strong> ${esc(line.text)}</p>`).join('')}${(turn.response?.suggestedChecks||[]).length?`<details><summary>Suggested unresolved checks</summary><pre>${esc(JSON.stringify(turn.response.suggestedChecks,null,2))}</pre></details>`:''}${safety?`<div class="dnd-ai-gm-lock"><strong>Safety ${esc(turn.response.safety.status)}</strong><p>${esc(turn.response.safety.reason)}</p></div>`:''}${suggestionRows(turn)}`:''}${turn.status==='failed'?`<div class="callout warning">${esc(turn.error)}</div>${turn.retryable?`<button class="button" data-ai-gm-action="retry" data-turn-id="${esc(turn.id)}">Retry Turn</button>`:''}`:''}</article>`; }
  function previewHtml(){ if(!state.preview)return '<div class="empty-state"><p>Preview the exact campaign copy before synchronizing it to Veyra.</p></div>'; return `<div class="dnd-ai-gm-preview"><span class="eyebrow">Exact synchronization preview</span><p><strong>${esc(state.preview.campaignName)}</strong> · ${esc(state.preview.sessionTitle)}</p><pre>${esc(state.preview.context?.preview||JSON.stringify(state.preview.request,null,2))}</pre><div class="callout warning">The separate AI service persists this campaign copy. No Discord identifiers, blind rolls, protected files, or unprovided licensed full text are included.</div><button class="button primary" data-ai-gm-action="sync">Confirm and Synchronize</button></div>`; }
  function studio(){ const session=activeSession(); const turns=(state.payload?.turns||[]).filter((item)=>!session||item.aiGmSessionId===session.id); return `<article class="panel dnd-ai-gm-studio" data-dnd-ai-gm-studio><div class="panel-heading"><div><span class="eyebrow">Veyra agent worker</span><h3>AI Game Master</h3><p>Explicit, review-first session assistance. The AI never rolls, publishes, or mutates campaign state automatically.</p></div><button class="button" data-ai-gm-action="refresh">Refresh</button></div>${!session?`<div class="dnd-ai-gm-grid"><form id="dndAiGmSyncForm"><label>Desktop session<select name="sessionId" required>${sessionOptions()}</select></label><div class="form-grid"><label class="toggle-row"><span>Include character details</span><input type="checkbox" name="includeCharacterDetails" checked></label><label class="toggle-row"><span>Include encounter details</span><input type="checkbox" name="includeEncounterDetails" checked></label><label class="toggle-row"><span>Include session recaps</span><input type="checkbox" name="includeSessionRecaps" checked></label><label class="toggle-row"><span>Include approved homebrew</span><input type="checkbox" name="includeApprovedHomebrew"></label><label class="toggle-row"><span>Include GM notes</span><input type="checkbox" name="includeGmNotes"></label></div><button class="button primary" type="button" data-ai-gm-action="preview">Preview Exact Campaign Copy</button></form>${previewHtml()}</div>`:`<div class="panel-heading"><div><span class="eyebrow">${esc(session.mode)}</span><h4>Session control</h4></div><span class="tag">${turns.length} turns</span></div>${session.safetyLocked?`<div class="dnd-ai-gm-lock"><strong>Generation paused by safety lock</strong><p>${esc(session.safetyReason)}</p><label>Reason to resume<textarea id="dndAiGmResumeReason" maxlength="1000"></textarea></label><button class="button" data-ai-gm-action="resume">Confirm Resume</button></div>`:`<form id="dndAiGmTurnForm"><div class="form-grid"><label>Actor<input name="actor" maxlength="100" value="Party"></label><label>Optional DM guidance<input name="dmGuidance" maxlength="4000"></label></div><label>Table action or statement<textarea name="message" maxlength="12000" rows="5" required></textarea></label><button class="button primary" type="button" data-ai-gm-action="turn">Confirm and Generate Turn</button></form>`}<div class="dnd-ai-gm-actions"><button class="button" data-ai-gm-action="recap">Draft Recap</button><button class="button danger" data-ai-gm-action="end">End AI GM Session</button></div><div class="dnd-ai-gm-history">${turns.length?turns.map(turnCard).join(''):'<div class="empty-state"><p>No AI Game Master turns yet.</p></div>'}</div>`}</article>`; }
  function enhance(){ const view=doc.getElementById('view-dnd'); if(!view)return; let mount=view.querySelector('[data-dnd-ai-gm-mount]'); if(!mount){ mount=doc.createElement('section'); mount.dataset.dndAiGmMount='1'; view.appendChild(mount); } mount.innerHTML=studio(); }
  async function action(event){ const button=event.target.closest('[data-ai-gm-action]'); if(!button||state.busy)return; const action=button.dataset.aiGmAction; try{ setBusy(true); if(action==='refresh')await refresh(true); else if(action==='preview'){ const form=doc.getElementById('dndAiGmSyncForm'); const data=new FormData(form); state.preview=await invoke('dnd:ai-gm-preview',{campaignId:state.campaignId,sessionId:clean(data.get('sessionId'),100),contextOptions:{includeCharacterDetails:data.has('includeCharacterDetails'),includeEncounterDetails:data.has('includeEncounterDetails'),includeSessionRecaps:data.has('includeSessionRecaps'),includeApprovedHomebrew:data.has('includeApprovedHomebrew'),includeGmNotes:data.has('includeGmNotes')}}); schedule(); } else if(action==='sync'){ await invoke('dnd:ai-gm-sync',{...state.preview,confirmed:true}); await refresh(true); notify('AI Game Master session synchronized.'); } else if(action==='turn'){ const session=activeSession(); const data=new FormData(doc.getElementById('dndAiGmTurnForm')); await invoke('dnd:ai-gm-turn',{aiGmSessionId:session.id,actor:clean(data.get('actor'),100),message:clean(data.get('message'),12000),dmGuidance:clean(data.get('dmGuidance'),4000),clientTurnId:crypto.randomUUID?.()||`${Date.now()}`,confirmed:true}); await refresh(true); } else if(action==='retry'){ await invoke('dnd:ai-gm-retry',{turnId:button.dataset.turnId,confirmed:true}); await refresh(true); } else if(action==='resume'){ await invoke('dnd:ai-gm-resume',{aiGmSessionId:activeSession().id,reason:clean(doc.getElementById('dndAiGmResumeReason')?.value,1000),confirmed:true}); await refresh(true); } else if(action==='apply'){ const turnId=button.dataset.turnId; const suggestionIds=[...doc.querySelectorAll(`[data-ai-gm-suggestion][data-turn-id="${CSS.escape(turnId)}"]:checked`)].map((item)=>item.dataset.aiGmSuggestion); const target=doc.querySelector(`[data-ai-gm-target="${CSS.escape(turnId)}"]`)?.value; await invoke('dnd:ai-gm-apply',{turnId,suggestionIds,target,confirmed:true}); await refresh(true); } else if(action==='recap'){ const result=await invoke('dnd:ai-gm-recap',{aiGmSessionId:activeSession().id}); await navigator.clipboard.writeText(result.text); notify('AI GM recap draft copied for review.'); } else if(action==='end'){ await invoke('dnd:ai-gm-end',{aiGmSessionId:activeSession().id,confirmed:true}); await refresh(true); } }catch(error){ notify(error.message||String(error)); }finally{ setBusy(false); } }
  doc.addEventListener('click',action);
  doc.addEventListener('change',(event)=>{ if(event.target?.id==='dndCampaignSelect'){ state.payload=null; refresh(true).catch(()=>{}); } });
  const observer=new MutationObserver(()=>schedule()); observer.observe(doc.documentElement,{childList:true,subtree:true});
  root.khaos?.on?.('dnd:ai-gm-update',(value)=>{ state.payload=value; state.campaignId=value.selectedCampaignId||state.campaignId; schedule(); });
  root.__khaosDndAiGm={refresh}; refresh(true).catch(()=>{}); schedule();
})(typeof window!=='undefined'?window:null);
