'use strict';

const { registerRoadmapGameModules } = require('./roadmap-game-module-registry.cjs');
const { installRetiredGamesSelfRoleCleanupExtension } = require('./retired-games-self-role-cleanup.cjs');
registerRoadmapGameModules();

const { installGuildMembersIntentExtension } = require('./guild-members-intent-extension.cjs');
const { installCommunityIntentsExtension } = require('./community-intents-extension.cjs');
const { installForgeExtension } = require('./forge-extension.cjs');
const { installForgeAuthProbeExtension } = require('./forge-auth-probe-extension.cjs');
const { installMentionResponseExtension } = require('./mention-response-extension.cjs');
const { installRoleMenuExtension } = require('./role-menu-extension.cjs');
const { installPokemonGoExtension } = require('./pokemon-go-extension.cjs');
const { installDivision2TargetedLootExtension } = require('./division2-targeted-loot-extension.cjs');
const { installEventFeedExtension } = require('./event-feed-extension.cjs');
const { installAdminPairingExtension } = require('./admin-pairing-extension.cjs');
const { installModerationExtension } = require('./moderation-extension.cjs');
const { installRoadmapPatchNoteExtension } = require('./roadmap-patch-note-extension.cjs');
const { installSafetyReportExtension } = require('./safety-report-extension.cjs');
const { installShieldExtension } = require('./shield-extension.cjs');
const { installShieldReviewExtension } = require('./shield-review-extension.cjs');
const { installShieldIsolationExtension } = require('./shield-isolation-extension.cjs');
const { installPersistentPanelExtension } = require('./persistent-panel-extension.cjs');
const { installStaffNameColorPreviewExtension } = require('./staff-name-color-preview-extension.cjs');
const { installNexusStatusExtension } = require('./nexus-status-extension.cjs');
const { installOnboardingAuthorityExtension } = require('./onboarding-authority-extension.cjs');
const { installWelcomeExtension } = require('./welcome-extension.cjs');
const { installAboutExtension } = require('./about-extension.cjs');
const { installRanksExtension } = require('./ranks-extension.cjs');
const { installSuggestionsExtension } = require('./suggestions-extension.cjs');
const { installSuggestionReviewExtension } = require('./suggestion-review-extension.cjs');
const { installGameServersExtension } = require('./game-servers-extension.cjs');
const { installHostedServerManagerExtension } = require('./hosted-server-manager-extension.cjs');
const { installCommunityLevelingExtension } = require('./community-leveling-extension.cjs');
const { installNexusCommandCenterExtension } = require('./nexus-command-center-extension.cjs');
const { installStaffWorkspaceExtension } = require('./staff-workspace-extension.cjs');
const { installModuleAutoprovisionExtension } = require('./module-autoprovision-extension.cjs');
const { installModuleAccessAuditExtension } = require('./module-access-audit-extension.cjs');
require('./poll-ui-readability-patch.cjs');
const { installPollExtension } = require('./poll-extension.cjs');
const { installCreatorLevelGateExtension } = require('./creator-level-gate-extension.cjs');
const { installCreatorProgramExtension } = require('./creator-program-extension.cjs');
const { installCreatorRolesEntryLockdownExtension } = require('./creator-roles-entry-lockdown-extension.cjs');
const { installCreatorLifecycleExtension } = require('./creator-lifecycle-extension.cjs');
const { installSupporterEntitlementExtension } = require('./supporter-entitlement-extension.cjs');
const { installEventManagementExtension } = require('./event-management-extension.cjs');
const { installArkOpsExtension } = require('./ark-ops-extension.cjs');
const { installArkUpdateSafetyExtension } = require('./ark-update-safety-extension.cjs');
const { installArkRestartSchedulerExtension } = require('./ark-restart-scheduler-extension.cjs');
const { installArkConfigDbExtension } = require('./ark-config-db-extension.cjs');
const { installArkClusterExtension } = require('./ark-cluster-extension.cjs');
const { installArkClusterMetadataExtension } = require('./ark-cluster-metadata-extension.cjs');
const { installArkConfigProfileExtension } = require('./ark-config-profile-extension.cjs');
const { installArkShopProfileExtension } = require('./arkshop-profile-extension.cjs');
const { installArkClusterPublicActions } = require('./ark-cluster-public-actions.cjs');
const { installArkShopProfileBootstrapExtension } = require('./arkshop-profile-bootstrap-extension.cjs');

installRetiredGamesSelfRoleCleanupExtension();
installGuildMembersIntentExtension();
installCommunityIntentsExtension();
installForgeExtension();
installForgeAuthProbeExtension();
installMentionResponseExtension();
installRoleMenuExtension();
installPokemonGoExtension();
installDivision2TargetedLootExtension();
installEventFeedExtension();
installAdminPairingExtension();
installModerationExtension();
installRoadmapPatchNoteExtension();
installSafetyReportExtension();
installShieldExtension();
installShieldReviewExtension();
installShieldIsolationExtension();
installPersistentPanelExtension();
installStaffNameColorPreviewExtension();
installNexusStatusExtension();
installOnboardingAuthorityExtension();
installWelcomeExtension();
installAboutExtension();
installRanksExtension();
installSuggestionsExtension();
installSuggestionReviewExtension();
installGameServersExtension();
installHostedServerManagerExtension();
installCommunityLevelingExtension();
installNexusCommandCenterExtension();
installStaffWorkspaceExtension();
installModuleAutoprovisionExtension();
installModuleAccessAuditExtension();
installPollExtension();
installCreatorLevelGateExtension();
installCreatorProgramExtension();
installCreatorRolesEntryLockdownExtension();
installCreatorLifecycleExtension();
installSupporterEntitlementExtension();
installEventManagementExtension();
installArkOpsExtension();
installArkUpdateSafetyExtension({ prefix: 'ARK_GEN1' });
installArkRestartSchedulerExtension({ prefix: 'ARK_GEN1' });
installArkConfigDbExtension();
installArkClusterExtension();
installArkClusterMetadataExtension();
installArkConfigProfileExtension();
installArkShopProfileExtension();
installArkClusterPublicActions();
installArkShopProfileBootstrapExtension();
require('./ark-cluster-plan-extension.cjs').installArkClusterPlanExtension();
require('./arkshop-nexus-economy-v1-runtime.cjs').installArkShopEconomyV1Runtime();
require('./arkshop-nexus-launch-v2-runtime.cjs').installArkShopLaunchV2Runtime();
require('./arkshop-nexus-launch-v3-kits-runtime.cjs').installArkShopLaunchV3KitsRuntime();
require('./arkshop-nexus-launch-v4-resources-runtime.cjs').installArkShopLaunchV4ResourcesRuntime();
require('./arkshop-nexus-launch-v5-disable-legacy-sell-runtime.cjs').installArkShopLaunchV5DisableLegacySellRuntime();
require('./arkshop-nexus-launch-v6-remove-demo-items-runtime.cjs').installArkShopLaunchV6RemoveDemoItemsRuntime();
require('./arkshop-nexus-launch-v7-basic-sell-runtime.cjs').installArkShopLaunchV7BasicSellRuntime();
require('./arkshop-nexus-launch-v8-boss-sell-runtime.cjs').installArkShopLaunchV8BossSellRuntime();
require('./arkshop-nexus-launch-v9-apex-tribute-sell-runtime.cjs').installArkShopLaunchV9ApexTributeSellRuntime();
require('./arkshop-nexus-launch-v10-native-item-delivery-runtime.cjs').installArkShopLaunchV10NativeItemDeliveryRuntime();
require('./arkshop-nexus-launch-v11-apothecary-runtime.cjs').installArkShopLaunchV11ApothecaryRuntime();
require('./arkshop-nexus-launch-v12-love-craft-fix-runtime.cjs').installArkShopLaunchV12LoveCraftFixRuntime();
require('./arkshop-map2-clone-from-gen1-runtime.cjs').installArkShopMap2CloneRuntime();
require('./natureshop-gen1-export-runtime.cjs').installNatureShopGen1ExportRuntime();
require('./arkshop-nexus-launch-v13-potion-balance-runtime.cjs').installArkShopLaunchV13PotionBalanceRuntime();
require('./arkshop-nexus-launch-v14-shadow-recruit-potion-prices-runtime.cjs').installArkShopLaunchV14PotionPricesRuntime();
require('./dinodepot-category-probe-runtime.cjs').installDinoDepotCategoryProbeRuntime();
require('./arkshop-ui-live-deploy-runtime.cjs').installArkShopUiLiveDeployRuntime();
require('./arkshop-cluster-economy-guard.cjs').installArkShopClusterEconomyGuard();
require('./arkshop-backend-preflight-runtime.cjs').installArkShopBackendPreflightRuntime();
require('./ark-command-routing-patch.cjs');
require('./bot.cjs');
