'use strict';

const { installGuildMembersIntentExtension } = require('./guild-members-intent-extension.cjs');
const { installCommunityIntentsExtension } = require('./community-intents-extension.cjs');
const { installRoleMenuExtension } = require('./role-menu-extension.cjs');
const { installPokemonGoExtension } = require('./pokemon-go-extension.cjs');
const { installEventFeedExtension } = require('./event-feed-extension.cjs');
const { installAdminPairingExtension } = require('./admin-pairing-extension.cjs');
const { installModerationExtension } = require('./moderation-extension.cjs');
const { installRoadmapPatchNoteExtension } = require('./roadmap-patch-note-extension.cjs');
const { installSafetyReportExtension } = require('./safety-report-extension.cjs');
const { installShieldExtension } = require('./shield-extension.cjs');
const { installShieldReviewExtension } = require('./shield-review-extension.cjs');
const { installShieldIsolationExtension } = require('./shield-isolation-extension.cjs');
const { installPersistentPanelExtension } = require('./persistent-panel-extension.cjs');
const { installStaffNameColorPreviewExtension } = require('./staff-name-color-preview-extension.cjs');
const { installNexusStatusExtension } = require('./nexus-status-extension.cjs');
const { installOnboardingAuthorityExtension } = require('./onboarding-authority-extension.cjs');
const { installWelcomeExtension } = require('./welcome-extension.cjs');
const { installAboutExtension } = require('./about-extension.cjs');
const { installRanksExtension } = require('./ranks-extension.cjs');
const { installSuggestionsExtension } = require('./suggestions-extension.cjs');
const { installSuggestionReviewExtension } = require('./suggestion-review-extension.cjs');
const { installGameServersExtension } = require('./game-servers-extension.cjs');
const { installCommunityLevelingExtension } = require('./community-leveling-extension.cjs');
const { installStaffWorkspaceExtension } = require('./staff-workspace-extension.cjs');
const { installModuleAutoprovisionExtension } = require('./module-autoprovision-extension.cjs');
const { installModuleAccessAuditExtension } = require('./module-access-audit-extension.cjs');
const { installPollExtension } = require('./poll-extension.cjs');
const { installCreatorProgramExtension } = require('./creator-program-extension.cjs');

installGuildMembersIntentExtension();
installCommunityIntentsExtension();
installRoleMenuExtension();
installPokemonGoExtension();
installEventFeedExtension();
installAdminPairingExtension();
installModerationExtension();
installRoadmapPatchNoteExtension();
installSafetyReportExtension();
installShieldExtension();
installShieldReviewExtension();
installShieldIsolationExtension();
installPersistentPanelExtension();
installStaffNameColorPreviewExtension();
installNexusStatusExtension();
installOnboardingAuthorityExtension();
installWelcomeExtension();
installAboutExtension();
installRanksExtension();
installSuggestionsExtension();
installSuggestionReviewExtension();
installGameServersExtension();
installCommunityLevelingExtension();
installStaffWorkspaceExtension();
installModuleAutoprovisionExtension();
installModuleAccessAuditExtension();
installPollExtension();
installCreatorProgramExtension();
require('./bot.cjs');
