'use strict';

const os = require('node:os');
const { redactObject, redactText } = require('../../shared/redaction.cjs');

function createDiagnosticReport({ appVersion, config, supervisorState, logs, secretValues }) {
  const safeLogs = logs.slice(-100).map((entry) => redactObject(entry, secretValues));
  return {
    generatedAt: new Date().toISOString(),
    application: {
      name: 'Khaos Nexus Bot Manager',
      version: appVersion,
      packaged: process.env.NODE_ENV !== 'development'
    },
    system: {
      platform: os.platform(),
      release: os.release(),
      architecture: os.arch(),
      cpuCount: os.cpus().length,
      totalMemoryMb: Math.round(os.totalmem() / 1024 / 1024)
    },
    configuration: redactObject(config, secretValues),
    runtime: redactObject(supervisorState, secretValues),
    recentLogs: safeLogs
  };
}

function reportAsMarkdown(report, maxLength = 4500) {
  const lastError = report.runtime.lastError;
  const logLines = report.recentLogs.slice(-30).map((entry) =>
    `[${entry.time}] [${entry.level}] [${entry.source}] ${entry.message}`
  ).join('\n');
  const body = [
    '## Khaos Nexus Bot Manager error report',
    '',
    `**App version:** ${report.application.version}`,
    `**System:** ${report.system.platform} ${report.system.release} (${report.system.architecture})`,
    `**Runtime status:** ${report.runtime.status}`,
    `**Error ID:** ${lastError?.id || 'No fingerprint captured'}`,
    `**Error:** ${lastError?.message || 'No error message captured'}`,
    '',
    '### Runtime snapshot',
    '```json',
    JSON.stringify({
      status: report.runtime.status,
      crashCount: report.runtime.crashCount,
      autoRestartBlocked: report.runtime.autoRestartBlocked,
      ready: report.runtime.ready,
      heartbeat: report.runtime.heartbeat
    }, null, 2),
    '```',
    '',
    '### Recent redacted logs',
    '```text',
    redactText(logLines),
    '```',
    '',
    '> Generated by the built-in Health Monitor. Credentials are redacted.'
  ].join('\n');
  return body.slice(0, maxLength);
}

module.exports = { createDiagnosticReport, reportAsMarkdown };
