const title=document.getElementById('title');const content=document.getElementById('content');const health=document.getElementById('health');let state=null;
const esc=(v)=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function load(){state=await window.nexusAdmin.state();health.textContent=state.backend?.ok?'Backend online':'Backend offline';health.className=state.backend?.ok?'good':'bad';show('overview')}
function cards(items){return `<div class="grid">${items.map(x=>`<article class="card"><h3>${esc(x.title)}</h3>${x.body}</article>`).join('')}</div>`}
function show(view){title.textContent=({overview:'Overview',discord:'Discord & Sentinel',accounts:'Accounts & Access',modules:'Backend Modules',diagnostics:'Diagnostics',thora:'Thora',settings:'Settings'})[view]||'Overview';
if(view==='overview')content.innerHTML=cards([{title:'Backend',body:`<p class="${state.backend?.ok?'good':'bad'}">${state.backend?.ok?'Online':'Offline'}</p>`},{title:'Sentinel',body:'<p>Primary game-module interface. Configure guild/channel bindings in config.json.</p>'},{title:'Desktop Scope',body:'<p>Administration, access, diagnostics and Thora only. Routine game UI stays out of Electron.</p>'}]);
if(view==='discord')content.innerHTML=cards([{title:'Sentinel Control',body:'<p>Persistent game-module consoles are owned by Nexus Sentinel. Channel bindings live in the rebuild configuration.</p>'},{title:'Discord Admin',body:'<p>Role/channel/permission administration ports into this surface without importing legacy game dashboards.</p>'}]);
if(view==='accounts')content.innerHTML=cards([{title:'Account Linking',body:'<p>Reserved for Discord OAuth/account mapping and global access policies.</p>'},{title:'Permissions',body:'<p>Viewer, operator and owner boundaries are shared with backend module capabilities.</p>'}]);
if(view==='modules'){const mods=state.modules?.modules||[];content.innerHTML=cards(mods.map(m=>({title:m.name,body:`<p>${m.enabled?'Enabled':'Disabled'} • ${m.configured?'<span class="good">Provider configured</span>':'<span class="warn">Provider setup needed</span>'}</p><p>${m.surface==='veyra'?'Veyra':'Sentinel'} surface</p>`})));}
if(view==='diagnostics')content.innerHTML='<div class="card"><div class="actions"><button id="runDiag">Run diagnostics</button></div><pre id="diag" class="mono"></pre></div>';
if(view==='thora')content.innerHTML=cards([{title:'Thora Bridge',body:`<p>${state.thora.enabled?'Enabled':'Disabled'} • ${state.thora.configured?'Path configured':'Path not configured'}</p><div class="actions"><button id="launchThora">Open Thora</button></div><p id="thoraMsg"></p>`}]);
if(view==='settings')content.innerHTML=cards([{title:'Configuration',body:`<p>Loaded from:</p><p class="mono">${esc(state.configSource)}</p><p>Secrets remain environment-backed; they are not displayed here.</p>`}]);
if(view==='diagnostics')document.getElementById('runDiag').onclick=async()=>document.getElementById('diag').textContent=JSON.stringify(await window.nexusAdmin.diagnostics(),null,2);
if(view==='thora')document.getElementById('launchThora').onclick=async()=>{try{await window.nexusAdmin.launchThora();document.getElementById('thoraMsg').textContent='Thora launch requested.'}catch(e){document.getElementById('thoraMsg').textContent=e.message}}}
document.querySelectorAll('nav button').forEach(btn=>btn.onclick=()=>show(btn.dataset.view));load().catch(e=>{content.textContent=e.message;health.textContent='Startup error';health.className='bad'});
